### ISSUE TITLE
Add new ways to validate data in node cases

### ISSUE THREAD

**Issue by egalvis39** [iKonoTelecomunicaciones/menuflow-old#4]
## Actual switch node

```yaml
    - id: switch-1
      type: switch
      validation: '{{ opt }}'
      validation_attempts: 3
      cases:
        - id: 1
          o_connection: m1
        - id: 2
          o_connection: m2
        - id: default
          o_connection: m3
        - id: attempt_exceeded
          o_connection: m4
 ```
## New feature

```yaml
    - id: switch-1
      type: switch
      validation: '{{ compare_ratio(opt, "Lorena Marulanda") }}'
      validation_attempts: 3
      cases:
        - case: "{% validation >= 80 %}"
          o_connection: m1
        - case: "{% validation > 30 and validation < 80 %}"
          o_connection: m2
        - id: default
          o_connection: m3
        - id: attempt_exceeded
          o_connection: m4
 ```
